{
  "cells": [
    {
      "cell_type": "code",
      "execution_count": 1,
      "metadata": {
        "id": "wfsuC-fnNlYX"
      },
      "outputs": [
        {
          "name": "stderr",
          "output_type": "stream",
          "text": [
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\mlflow\\utils\\requirements_utils.py:20: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.\n",
            "  import pkg_resources  # noqa: TID251\n"
          ]
        }
      ],
      "source": [
        "import mlflow\n",
        "mlflow.set_tracking_uri(\"http://13.221.75.66:5000/\")"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 2,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "ZI0XrT5vOA51",
        "outputId": "7e8ca094-5a35-478c-8d1e-08d5658e8a7a"
      },
      "outputs": [
        {
          "ename": "KeyboardInterrupt",
          "evalue": "",
          "output_type": "error",
          "traceback": [
            "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
            "\u001b[1;31mKeyboardInterrupt\u001b[0m                         Traceback (most recent call last)",
            "Cell \u001b[1;32mIn[2], line 4\u001b[0m\n\u001b[0;32m      1\u001b[0m \u001b[38;5;28;01mimport\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;21;01mmlflow\u001b[39;00m\n\u001b[0;32m      3\u001b[0m \u001b[38;5;66;03m# Set experiment before logging anything\u001b[39;00m\n\u001b[1;32m----> 4\u001b[0m \u001b[43mmlflow\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mset_experiment\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43mML Algos with HPT\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m)\u001b[49m\n\u001b[0;32m      6\u001b[0m \u001b[38;5;28;01mwith\u001b[39;00m mlflow\u001b[38;5;241m.\u001b[39mstart_run():\n\u001b[0;32m      7\u001b[0m     mlflow\u001b[38;5;241m.\u001b[39mlog_param(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mexample_param\u001b[39m\u001b[38;5;124m\"\u001b[39m, \u001b[38;5;241m42\u001b[39m)\n",
            "File \u001b[1;32mc:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\mlflow\\tracking\\fluent.py:143\u001b[0m, in \u001b[0;36mset_experiment\u001b[1;34m(experiment_name, experiment_id)\u001b[0m\n\u001b[0;32m    141\u001b[0m client \u001b[38;5;241m=\u001b[39m MlflowClient()\n\u001b[0;32m    142\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m experiment_id \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n\u001b[1;32m--> 143\u001b[0m     experiment \u001b[38;5;241m=\u001b[39m \u001b[43mclient\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mget_experiment_by_name\u001b[49m\u001b[43m(\u001b[49m\u001b[43mexperiment_name\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m    144\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m experiment:\n\u001b[0;32m    145\u001b[0m         _logger\u001b[38;5;241m.\u001b[39minfo(\n\u001b[0;32m    146\u001b[0m             \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mExperiment with name \u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;132;01m%s\u001b[39;00m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124m does not exist. Creating a new experiment.\u001b[39m\u001b[38;5;124m\"\u001b[39m,\n\u001b[0;32m    147\u001b[0m             experiment_name,\n\u001b[0;32m    148\u001b[0m         )\n",
            "File \u001b[1;32mc:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\mlflow\\tracking\\client.py:1241\u001b[0m, in \u001b[0;36mMlflowClient.get_experiment_by_name\u001b[1;34m(self, name)\u001b[0m\n\u001b[0;32m   1209\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;21mget_experiment_by_name\u001b[39m(\u001b[38;5;28mself\u001b[39m, name: \u001b[38;5;28mstr\u001b[39m) \u001b[38;5;241m-\u001b[39m\u001b[38;5;241m>\u001b[39m Optional[Experiment]:\n\u001b[0;32m   1210\u001b[0m \u001b[38;5;250m    \u001b[39m\u001b[38;5;124;03m\"\"\"Retrieve an experiment by experiment name from the backend store\u001b[39;00m\n\u001b[0;32m   1211\u001b[0m \n\u001b[0;32m   1212\u001b[0m \u001b[38;5;124;03m    Args:\u001b[39;00m\n\u001b[1;32m   (...)\u001b[0m\n\u001b[0;32m   1239\u001b[0m \u001b[38;5;124;03m        Lifecycle_stage: active\u001b[39;00m\n\u001b[0;32m   1240\u001b[0m \u001b[38;5;124;03m    \"\"\"\u001b[39;00m\n\u001b[1;32m-> 1241\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_tracking_client\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mget_experiment_by_name\u001b[49m\u001b[43m(\u001b[49m\u001b[43mname\u001b[49m\u001b[43m)\u001b[49m\n",
            "File \u001b[1;32mc:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\mlflow\\tracking\\_tracking_service\\client.py:482\u001b[0m, in \u001b[0;36mTrackingServiceClient.get_experiment_by_name\u001b[1;34m(self, name)\u001b[0m\n\u001b[0;32m    474\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;21mget_experiment_by_name\u001b[39m(\u001b[38;5;28mself\u001b[39m, name):\n\u001b[0;32m    475\u001b[0m \u001b[38;5;250m    \u001b[39m\u001b[38;5;124;03m\"\"\"\u001b[39;00m\n\u001b[0;32m    476\u001b[0m \u001b[38;5;124;03m    Args:\u001b[39;00m\n\u001b[0;32m    477\u001b[0m \u001b[38;5;124;03m        name: The experiment name.\u001b[39;00m\n\u001b[1;32m   (...)\u001b[0m\n\u001b[0;32m    480\u001b[0m \u001b[38;5;124;03m        :py:class:`mlflow.entities.Experiment`\u001b[39;00m\n\u001b[0;32m    481\u001b[0m \u001b[38;5;124;03m    \"\"\"\u001b[39;00m\n\u001b[1;32m--> 482\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mstore\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mget_experiment_by_name\u001b[49m\u001b[43m(\u001b[49m\u001b[43mname\u001b[49m\u001b[43m)\u001b[49m\n",
            "File \u001b[1;32mc:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\mlflow\\store\\tracking\\rest_store.py:518\u001b[0m, in \u001b[0;36mRestStore.get_experiment_by_name\u001b[1;34m(self, experiment_name)\u001b[0m\n\u001b[0;32m    516\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[0;32m    517\u001b[0m     req_body \u001b[38;5;241m=\u001b[39m message_to_json(GetExperimentByName(experiment_name\u001b[38;5;241m=\u001b[39mexperiment_name))\n\u001b[1;32m--> 518\u001b[0m     response_proto \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_call_endpoint\u001b[49m\u001b[43m(\u001b[49m\u001b[43mGetExperimentByName\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mreq_body\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m    519\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m Experiment\u001b[38;5;241m.\u001b[39mfrom_proto(response_proto\u001b[38;5;241m.\u001b[39mexperiment)\n\u001b[0;32m    520\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m MlflowException \u001b[38;5;28;01mas\u001b[39;00m e:\n",
            "File \u001b[1;32mc:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\mlflow\\store\\tracking\\rest_store.py:81\u001b[0m, in \u001b[0;36mRestStore._call_endpoint\u001b[1;34m(self, api, json_body, endpoint)\u001b[0m\n\u001b[0;32m     79\u001b[0m     endpoint, method \u001b[38;5;241m=\u001b[39m _METHOD_TO_INFO[api]\n\u001b[0;32m     80\u001b[0m response_proto \u001b[38;5;241m=\u001b[39m api\u001b[38;5;241m.\u001b[39mResponse()\n\u001b[1;32m---> 81\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[43mcall_endpoint\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mget_host_creds\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mendpoint\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mmethod\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mjson_body\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mresponse_proto\u001b[49m\u001b[43m)\u001b[49m\n",
            "File \u001b[1;32mc:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\mlflow\\utils\\rest_utils.py:299\u001b[0m, in \u001b[0;36mcall_endpoint\u001b[1;34m(host_creds, endpoint, method, json_body, response_proto, extra_headers)\u001b[0m\n\u001b[0;32m    297\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m method \u001b[38;5;241m==\u001b[39m \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mGET\u001b[39m\u001b[38;5;124m\"\u001b[39m:\n\u001b[0;32m    298\u001b[0m     call_kwargs[\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mparams\u001b[39m\u001b[38;5;124m\"\u001b[39m] \u001b[38;5;241m=\u001b[39m json_body\n\u001b[1;32m--> 299\u001b[0m     response \u001b[38;5;241m=\u001b[39m http_request(\u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mcall_kwargs)\n\u001b[0;32m    300\u001b[0m \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[0;32m    301\u001b[0m     call_kwargs[\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mjson\u001b[39m\u001b[38;5;124m\"\u001b[39m] \u001b[38;5;241m=\u001b[39m json_body\n",
            "File \u001b[1;32mc:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\mlflow\\utils\\rest_utils.py:129\u001b[0m, in \u001b[0;36mhttp_request\u001b[1;34m(host_creds, endpoint, method, max_retries, backoff_factor, backoff_jitter, extra_headers, retry_codes, timeout, raise_on_status, respect_retry_after_header, **kwargs)\u001b[0m\n\u001b[0;32m    127\u001b[0m url \u001b[38;5;241m=\u001b[39m \u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;132;01m{\u001b[39;00mcleaned_hostname\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;132;01m{\u001b[39;00mendpoint\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m\"\u001b[39m\n\u001b[0;32m    128\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[1;32m--> 129\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m _get_http_response_with_retries(\n\u001b[0;32m    130\u001b[0m         method,\n\u001b[0;32m    131\u001b[0m         url,\n\u001b[0;32m    132\u001b[0m         max_retries,\n\u001b[0;32m    133\u001b[0m         backoff_factor,\n\u001b[0;32m    134\u001b[0m         backoff_jitter,\n\u001b[0;32m    135\u001b[0m         retry_codes,\n\u001b[0;32m    136\u001b[0m         raise_on_status,\n\u001b[0;32m    137\u001b[0m         headers\u001b[38;5;241m=\u001b[39mheaders,\n\u001b[0;32m    138\u001b[0m         verify\u001b[38;5;241m=\u001b[39mhost_creds\u001b[38;5;241m.\u001b[39mverify,\n\u001b[0;32m    139\u001b[0m         timeout\u001b[38;5;241m=\u001b[39mtimeout,\n\u001b[0;32m    140\u001b[0m         respect_retry_after_header\u001b[38;5;241m=\u001b[39mrespect_retry_after_header,\n\u001b[0;32m    141\u001b[0m         \u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mkwargs,\n\u001b[0;32m    142\u001b[0m     )\n\u001b[0;32m    143\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m requests\u001b[38;5;241m.\u001b[39mexceptions\u001b[38;5;241m.\u001b[39mTimeout \u001b[38;5;28;01mas\u001b[39;00m to:\n\u001b[0;32m    144\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m MlflowException(\n\u001b[0;32m    145\u001b[0m         \u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mAPI request to \u001b[39m\u001b[38;5;132;01m{\u001b[39;00murl\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m failed with timeout exception \u001b[39m\u001b[38;5;132;01m{\u001b[39;00mto\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m.\u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[0;32m    146\u001b[0m         \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124m To increase the timeout, set the environment variable \u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[0;32m    147\u001b[0m         \u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;132;01m{\u001b[39;00mMLFLOW_HTTP_REQUEST_TIMEOUT\u001b[38;5;132;01m!s}\u001b[39;00m\u001b[38;5;124m to a larger value.\u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[0;32m    148\u001b[0m     ) \u001b[38;5;28;01mfrom\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;21;01mto\u001b[39;00m\n",
            "File \u001b[1;32mc:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\mlflow\\utils\\request_utils.py:237\u001b[0m, in \u001b[0;36m_get_http_response_with_retries\u001b[1;34m(method, url, max_retries, backoff_factor, backoff_jitter, retry_codes, raise_on_status, allow_redirects, respect_retry_after_header, **kwargs)\u001b[0m\n\u001b[0;32m    234\u001b[0m env_value \u001b[38;5;241m=\u001b[39m os\u001b[38;5;241m.\u001b[39mgetenv(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mMLFLOW_ALLOW_HTTP_REDIRECTS\u001b[39m\u001b[38;5;124m\"\u001b[39m, \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mtrue\u001b[39m\u001b[38;5;124m\"\u001b[39m)\u001b[38;5;241m.\u001b[39mlower() \u001b[38;5;129;01min\u001b[39;00m [\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mtrue\u001b[39m\u001b[38;5;124m\"\u001b[39m, \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124m1\u001b[39m\u001b[38;5;124m\"\u001b[39m]\n\u001b[0;32m    235\u001b[0m allow_redirects \u001b[38;5;241m=\u001b[39m env_value \u001b[38;5;28;01mif\u001b[39;00m allow_redirects \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m \u001b[38;5;28;01melse\u001b[39;00m allow_redirects\n\u001b[1;32m--> 237\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m session\u001b[38;5;241m.\u001b[39mrequest(method, url, allow_redirects\u001b[38;5;241m=\u001b[39mallow_redirects, \u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mkwargs)\n",
            "File \u001b[1;32mc:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\requests\\sessions.py:589\u001b[0m, in \u001b[0;36mSession.request\u001b[1;34m(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)\u001b[0m\n\u001b[0;32m    584\u001b[0m send_kwargs \u001b[38;5;241m=\u001b[39m {\n\u001b[0;32m    585\u001b[0m     \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mtimeout\u001b[39m\u001b[38;5;124m\"\u001b[39m: timeout,\n\u001b[0;32m    586\u001b[0m     \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mallow_redirects\u001b[39m\u001b[38;5;124m\"\u001b[39m: allow_redirects,\n\u001b[0;32m    587\u001b[0m }\n\u001b[0;32m    588\u001b[0m send_kwargs\u001b[38;5;241m.\u001b[39mupdate(settings)\n\u001b[1;32m--> 589\u001b[0m resp \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39msend(prep, \u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39msend_kwargs)\n\u001b[0;32m    591\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m resp\n",
            "File \u001b[1;32mc:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\requests\\sessions.py:703\u001b[0m, in \u001b[0;36mSession.send\u001b[1;34m(self, request, **kwargs)\u001b[0m\n\u001b[0;32m    700\u001b[0m start \u001b[38;5;241m=\u001b[39m preferred_clock()\n\u001b[0;32m    702\u001b[0m \u001b[38;5;66;03m# Send the request\u001b[39;00m\n\u001b[1;32m--> 703\u001b[0m r \u001b[38;5;241m=\u001b[39m adapter\u001b[38;5;241m.\u001b[39msend(request, \u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mkwargs)\n\u001b[0;32m    705\u001b[0m \u001b[38;5;66;03m# Total elapsed time of the request (approximately)\u001b[39;00m\n\u001b[0;32m    706\u001b[0m elapsed \u001b[38;5;241m=\u001b[39m preferred_clock() \u001b[38;5;241m-\u001b[39m start\n",
            "File \u001b[1;32mc:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\requests\\adapters.py:667\u001b[0m, in \u001b[0;36mHTTPAdapter.send\u001b[1;34m(self, request, stream, timeout, verify, cert, proxies)\u001b[0m\n\u001b[0;32m    664\u001b[0m     timeout \u001b[38;5;241m=\u001b[39m TimeoutSauce(connect\u001b[38;5;241m=\u001b[39mtimeout, read\u001b[38;5;241m=\u001b[39mtimeout)\n\u001b[0;32m    666\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[1;32m--> 667\u001b[0m     resp \u001b[38;5;241m=\u001b[39m \u001b[43mconn\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43murlopen\u001b[49m\u001b[43m(\u001b[49m\n\u001b[0;32m    668\u001b[0m \u001b[43m        \u001b[49m\u001b[43mmethod\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mrequest\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mmethod\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m    669\u001b[0m \u001b[43m        \u001b[49m\u001b[43murl\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43murl\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m    670\u001b[0m \u001b[43m        \u001b[49m\u001b[43mbody\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mrequest\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mbody\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m    671\u001b[0m \u001b[43m        \u001b[49m\u001b[43mheaders\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mrequest\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mheaders\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m    672\u001b[0m \u001b[43m        \u001b[49m\u001b[43mredirect\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;28;43;01mFalse\u001b[39;49;00m\u001b[43m,\u001b[49m\n\u001b[0;32m    673\u001b[0m \u001b[43m        \u001b[49m\u001b[43massert_same_host\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;28;43;01mFalse\u001b[39;49;00m\u001b[43m,\u001b[49m\n\u001b[0;32m    674\u001b[0m \u001b[43m        \u001b[49m\u001b[43mpreload_content\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;28;43;01mFalse\u001b[39;49;00m\u001b[43m,\u001b[49m\n\u001b[0;32m    675\u001b[0m \u001b[43m        \u001b[49m\u001b[43mdecode_content\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;28;43;01mFalse\u001b[39;49;00m\u001b[43m,\u001b[49m\n\u001b[0;32m    676\u001b[0m \u001b[43m        \u001b[49m\u001b[43mretries\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mmax_retries\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m    677\u001b[0m \u001b[43m        \u001b[49m\u001b[43mtimeout\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mtimeout\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m    678\u001b[0m \u001b[43m        \u001b[49m\u001b[43mchunked\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mchunked\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m    679\u001b[0m \u001b[43m    \u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m    681\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m (ProtocolError, \u001b[38;5;167;01mOSError\u001b[39;00m) \u001b[38;5;28;01mas\u001b[39;00m err:\n\u001b[0;32m    682\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mConnectionError\u001b[39;00m(err, request\u001b[38;5;241m=\u001b[39mrequest)\n",
            "File \u001b[1;32mc:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\urllib3\\connectionpool.py:787\u001b[0m, in \u001b[0;36mHTTPConnectionPool.urlopen\u001b[1;34m(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, preload_content, decode_content, **response_kw)\u001b[0m\n\u001b[0;32m    784\u001b[0m response_conn \u001b[38;5;241m=\u001b[39m conn \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m release_conn \u001b[38;5;28;01melse\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m\n\u001b[0;32m    786\u001b[0m \u001b[38;5;66;03m# Make the request on the HTTPConnection object\u001b[39;00m\n\u001b[1;32m--> 787\u001b[0m response \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_make_request(\n\u001b[0;32m    788\u001b[0m     conn,\n\u001b[0;32m    789\u001b[0m     method,\n\u001b[0;32m    790\u001b[0m     url,\n\u001b[0;32m    791\u001b[0m     timeout\u001b[38;5;241m=\u001b[39mtimeout_obj,\n\u001b[0;32m    792\u001b[0m     body\u001b[38;5;241m=\u001b[39mbody,\n\u001b[0;32m    793\u001b[0m     headers\u001b[38;5;241m=\u001b[39mheaders,\n\u001b[0;32m    794\u001b[0m     chunked\u001b[38;5;241m=\u001b[39mchunked,\n\u001b[0;32m    795\u001b[0m     retries\u001b[38;5;241m=\u001b[39mretries,\n\u001b[0;32m    796\u001b[0m     response_conn\u001b[38;5;241m=\u001b[39mresponse_conn,\n\u001b[0;32m    797\u001b[0m     preload_content\u001b[38;5;241m=\u001b[39mpreload_content,\n\u001b[0;32m    798\u001b[0m     decode_content\u001b[38;5;241m=\u001b[39mdecode_content,\n\u001b[0;32m    799\u001b[0m     \u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mresponse_kw,\n\u001b[0;32m    800\u001b[0m )\n\u001b[0;32m    802\u001b[0m \u001b[38;5;66;03m# Everything went great!\u001b[39;00m\n\u001b[0;32m    803\u001b[0m clean_exit \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;01mTrue\u001b[39;00m\n",
            "File \u001b[1;32mc:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\urllib3\\connectionpool.py:534\u001b[0m, in \u001b[0;36mHTTPConnectionPool._make_request\u001b[1;34m(self, conn, method, url, body, headers, retries, timeout, chunked, response_conn, preload_content, decode_content, enforce_content_length)\u001b[0m\n\u001b[0;32m    532\u001b[0m \u001b[38;5;66;03m# Receive the response from the server\u001b[39;00m\n\u001b[0;32m    533\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[1;32m--> 534\u001b[0m     response \u001b[38;5;241m=\u001b[39m \u001b[43mconn\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mgetresponse\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m    535\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m (BaseSSLError, \u001b[38;5;167;01mOSError\u001b[39;00m) \u001b[38;5;28;01mas\u001b[39;00m e:\n\u001b[0;32m    536\u001b[0m     \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_raise_timeout(err\u001b[38;5;241m=\u001b[39me, url\u001b[38;5;241m=\u001b[39murl, timeout_value\u001b[38;5;241m=\u001b[39mread_timeout)\n",
            "File \u001b[1;32mc:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\urllib3\\connection.py:565\u001b[0m, in \u001b[0;36mHTTPConnection.getresponse\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m    562\u001b[0m _shutdown \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mgetattr\u001b[39m(\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39msock, \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mshutdown\u001b[39m\u001b[38;5;124m\"\u001b[39m, \u001b[38;5;28;01mNone\u001b[39;00m)\n\u001b[0;32m    564\u001b[0m \u001b[38;5;66;03m# Get the response from http.client.HTTPConnection\u001b[39;00m\n\u001b[1;32m--> 565\u001b[0m httplib_response \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;43msuper\u001b[39;49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mgetresponse\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m    567\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[0;32m    568\u001b[0m     assert_header_parsing(httplib_response\u001b[38;5;241m.\u001b[39mmsg)\n",
            "File \u001b[1;32mc:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\http\\client.py:1375\u001b[0m, in \u001b[0;36mHTTPConnection.getresponse\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m   1373\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[0;32m   1374\u001b[0m     \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[1;32m-> 1375\u001b[0m         \u001b[43mresponse\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mbegin\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m   1376\u001b[0m     \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mConnectionError\u001b[39;00m:\n\u001b[0;32m   1377\u001b[0m         \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mclose()\n",
            "File \u001b[1;32mc:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\http\\client.py:318\u001b[0m, in \u001b[0;36mHTTPResponse.begin\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m    316\u001b[0m \u001b[38;5;66;03m# read until we get a non-100 response\u001b[39;00m\n\u001b[0;32m    317\u001b[0m \u001b[38;5;28;01mwhile\u001b[39;00m \u001b[38;5;28;01mTrue\u001b[39;00m:\n\u001b[1;32m--> 318\u001b[0m     version, status, reason \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_read_status\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m    319\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m status \u001b[38;5;241m!=\u001b[39m CONTINUE:\n\u001b[0;32m    320\u001b[0m         \u001b[38;5;28;01mbreak\u001b[39;00m\n",
            "File \u001b[1;32mc:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\http\\client.py:279\u001b[0m, in \u001b[0;36mHTTPResponse._read_status\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m    278\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;21m_read_status\u001b[39m(\u001b[38;5;28mself\u001b[39m):\n\u001b[1;32m--> 279\u001b[0m     line \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mstr\u001b[39m(\u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mfp\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mreadline\u001b[49m\u001b[43m(\u001b[49m\u001b[43m_MAXLINE\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m+\u001b[39;49m\u001b[43m \u001b[49m\u001b[38;5;241;43m1\u001b[39;49m\u001b[43m)\u001b[49m, \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124miso-8859-1\u001b[39m\u001b[38;5;124m\"\u001b[39m)\n\u001b[0;32m    280\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28mlen\u001b[39m(line) \u001b[38;5;241m>\u001b[39m _MAXLINE:\n\u001b[0;32m    281\u001b[0m         \u001b[38;5;28;01mraise\u001b[39;00m LineTooLong(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mstatus line\u001b[39m\u001b[38;5;124m\"\u001b[39m)\n",
            "File \u001b[1;32mc:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\socket.py:717\u001b[0m, in \u001b[0;36mSocketIO.readinto\u001b[1;34m(self, b)\u001b[0m\n\u001b[0;32m    715\u001b[0m \u001b[38;5;28;01mwhile\u001b[39;00m \u001b[38;5;28;01mTrue\u001b[39;00m:\n\u001b[0;32m    716\u001b[0m     \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[1;32m--> 717\u001b[0m         \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_sock\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mrecv_into\u001b[49m\u001b[43m(\u001b[49m\u001b[43mb\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m    718\u001b[0m     \u001b[38;5;28;01mexcept\u001b[39;00m timeout:\n\u001b[0;32m    719\u001b[0m         \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_timeout_occurred \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;01mTrue\u001b[39;00m\n",
            "\u001b[1;31mKeyboardInterrupt\u001b[0m: "
          ]
        }
      ],
      "source": [
        "import mlflow\n",
        "\n",
        "# Set experiment before logging anything\n",
        "mlflow.set_experiment(\"ML Algos with HPT\")\n",
        "\n",
        "with mlflow.start_run():\n",
        "    mlflow.log_param(\"example_param\", 42)\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 3,
      "metadata": {
        "id": "ltFvs55aNwjm"
      },
      "outputs": [],
      "source": [
        "import optuna\n",
        "import mlflow\n",
        "import mlflow.sklearn\n",
        "from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer\n",
        "from sklearn.linear_model import LogisticRegression\n",
        "from sklearn.svm import SVC\n",
        "from sklearn.neighbors import KNeighborsClassifier\n",
        "from xgboost import XGBClassifier\n",
        "from lightgbm import LGBMClassifier\n",
        "from sklearn.naive_bayes import MultinomialNB\n",
        "from sklearn.ensemble import RandomForestClassifier\n",
        "from sklearn.model_selection import train_test_split\n",
        "from imblearn.over_sampling import SMOTE\n",
        "from sklearn.metrics import accuracy_score, classification_report\n",
        "import pandas as pd\n",
        "import mlflow.sklearn\n",
        "import seaborn as sns\n",
        "import matplotlib.pyplot as plt\n",
        "import os\n",
        "import pandas as pd"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 4,
      "metadata": {
        "id": "OK-8fFDLOGh-"
      },
      "outputs": [
        {
          "data": {
            "text/plain": [
              "(36750, 7)"
            ]
          },
          "execution_count": 4,
          "metadata": {},
          "output_type": "execute_result"
        }
      ],
      "source": [
        "df= pd.read_csv(r'C:\\Users\\Deepu\\OneDrive\\Desktop\\Capstone1\\reddit_preprocessing.csv').dropna()\n",
        "df.shape"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 21,
      "metadata": {},
      "outputs": [],
      "source": [
        "# Instantiate LightGBM classifier correctly\n",
        "lgb = LGBMClassifier()"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 22,
      "metadata": {},
      "outputs": [],
      "source": [
        "X_cleaned = df['clean_comment']\n",
        "y_cleaned = df['category'] "
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 23,
      "metadata": {},
      "outputs": [],
      "source": [
        "# Step 5: Train-test split\n",
        "X_train_cleaned, X_test_cleaned, y_train_cleaned, y_test_cleaned = train_test_split(\n",
        "    X_cleaned, y_cleaned, test_size=0.2, random_state=42\n",
        ")\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 24,
      "metadata": {},
      "outputs": [],
      "source": [
        "ngram_range = (1, 3)  # Trigram\n",
        "max_features = 10000\n",
        "TF_IDF_cleaned = TfidfVectorizer(ngram_range=ngram_range, max_features=max_features)"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 25,
      "metadata": {},
      "outputs": [],
      "source": [
        "X_train_tfidf_cleaned = TF_IDF_cleaned.fit_transform(X_train_cleaned)\n",
        "X_test_tfidf_cleaned = TF_IDF_cleaned.transform(X_test_cleaned)"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 27,
      "metadata": {},
      "outputs": [],
      "source": [
        "import optuna\n",
        "import lightgbm as lgb\n",
        "from sklearn.model_selection import cross_val_score\n",
        "from sklearn.metrics import accuracy_score, classification_report"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 28,
      "metadata": {},
      "outputs": [],
      "source": [
        "# Function to optimize LightGBM hyperparameters\n",
        "def objective(trial):\n",
        "    # Define hyperparameters to be tuned\n",
        "    param = {\n",
        "        \"objective\": \"multiclass\",\n",
        "        \"num_class\": 3,  # Assuming 3 categories (-1, 0, 1)\n",
        "        \"learning_rate\": trial.suggest_float(\"learning_rate\", 1e-3, 1e-1),\n",
        "        \"n_estimators\": trial.suggest_int(\"n_estimators\", 50, 500),\n",
        "        \"max_depth\": trial.suggest_int(\"max_depth\", 3, 20),\n",
        "        \"metric\": \"multi_logloss\",\n",
        "        \"is_unbalance\": True,\n",
        "        \"class_weight\": \"balanced\"\n",
        "    }\n",
        "\n",
        "    # Define the LightGBM model with the trial parameters\n",
        "    model = lgb.LGBMClassifier(**param)\n",
        "\n",
        "    # Perform cross-validation\n",
        "    scores = cross_val_score(model, X_train_tfidf_cleaned, y_train_cleaned, cv=3, scoring='accuracy')\n",
        "\n",
        "    # Return the average score across folds\n",
        "    return scores.mean()\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 29,
      "metadata": {},
      "outputs": [
        {
          "name": "stderr",
          "output_type": "stream",
          "text": [
            "[I 2025-08-15 15:22:05,763] A new study created in memory with name: no-name-7f3abf6b-b25f-4f78-93df-8fc00000c9bd\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "[I 2025-08-15 15:22:15,399] Trial 0 finished with value: 0.8452698860029959 and parameters: {'learning_rate': 0.010832654959957468, 'n_estimators': 118, 'max_depth': 16}. Best is trial 0 with value: 0.8452698860029959.\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "[I 2025-08-15 15:22:15,399] Trial 0 finished with value: 0.8452698860029959 and parameters: {'learning_rate': 0.010832654959957468, 'n_estimators': 118, 'max_depth': 16}. Best is trial 0 with value: 0.8452698860029959.\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "[I 2025-08-15 15:22:22,028] Trial 1 finished with value: 0.8950045007928319 and parameters: {'learning_rate': 0.058333709723909465, 'n_estimators': 115, 'max_depth': 8}. Best is trial 1 with value: 0.8950045007928319.\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "[I 2025-08-15 15:22:22,028] Trial 1 finished with value: 0.8950045007928319 and parameters: {'learning_rate': 0.058333709723909465, 'n_estimators': 115, 'max_depth': 8}. Best is trial 1 with value: 0.8950045007928319.\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "[I 2025-08-15 15:22:38,823] Trial 2 finished with value: 0.9441252247511293 and parameters: {'learning_rate': 0.05881366285151204, 'n_estimators': 265, 'max_depth': 13}. Best is trial 2 with value: 0.9441252247511293.\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "[I 2025-08-15 15:22:38,823] Trial 2 finished with value: 0.9441252247511293 and parameters: {'learning_rate': 0.05881366285151204, 'n_estimators': 265, 'max_depth': 13}. Best is trial 2 with value: 0.9441252247511293.\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "[I 2025-08-15 15:22:45,256] Trial 3 finished with value: 0.9223716985530528 and parameters: {'learning_rate': 0.06413118844491364, 'n_estimators': 81, 'max_depth': 20}. Best is trial 2 with value: 0.9441252247511293.\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "[I 2025-08-15 15:22:45,256] Trial 3 finished with value: 0.9223716985530528 and parameters: {'learning_rate': 0.06413118844491364, 'n_estimators': 81, 'max_depth': 20}. Best is trial 2 with value: 0.9441252247511293.\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "[I 2025-08-15 15:22:54,801] Trial 4 finished with value: 0.9418884518888326 and parameters: {'learning_rate': 0.08907851211271688, 'n_estimators': 150, 'max_depth': 13}. Best is trial 2 with value: 0.9441252247511293.\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "[I 2025-08-15 15:22:54,801] Trial 4 finished with value: 0.9418884518888326 and parameters: {'learning_rate': 0.08907851211271688, 'n_estimators': 150, 'max_depth': 13}. Best is trial 2 with value: 0.9441252247511293.\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "[I 2025-08-15 15:23:11,469] Trial 5 finished with value: 0.9506601220522692 and parameters: {'learning_rate': 0.07631670505764626, 'n_estimators': 276, 'max_depth': 15}. Best is trial 5 with value: 0.9506601220522692.\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "[I 2025-08-15 15:23:11,469] Trial 5 finished with value: 0.9506601220522692 and parameters: {'learning_rate': 0.07631670505764626, 'n_estimators': 276, 'max_depth': 15}. Best is trial 5 with value: 0.9506601220522692.\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "[I 2025-08-15 15:23:22,082] Trial 6 finished with value: 0.8612340019895811 and parameters: {'learning_rate': 0.014746702198237618, 'n_estimators': 142, 'max_depth': 13}. Best is trial 5 with value: 0.9506601220522692.\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "[I 2025-08-15 15:23:22,082] Trial 6 finished with value: 0.8612340019895811 and parameters: {'learning_rate': 0.014746702198237618, 'n_estimators': 142, 'max_depth': 13}. Best is trial 5 with value: 0.9506601220522692.\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "[I 2025-08-15 15:23:31,361] Trial 7 finished with value: 0.9403096026146144 and parameters: {'learning_rate': 0.08829752882305487, 'n_estimators': 135, 'max_depth': 14}. Best is trial 5 with value: 0.9506601220522692.\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "[I 2025-08-15 15:23:31,361] Trial 7 finished with value: 0.9403096026146144 and parameters: {'learning_rate': 0.08829752882305487, 'n_estimators': 135, 'max_depth': 14}. Best is trial 5 with value: 0.9506601220522692.\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "[I 2025-08-15 15:23:50,318] Trial 8 finished with value: 0.84241918191743 and parameters: {'learning_rate': 0.004644220221410866, 'n_estimators': 227, 'max_depth': 18}. Best is trial 5 with value: 0.9506601220522692.\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "[I 2025-08-15 15:23:50,318] Trial 8 finished with value: 0.84241918191743 and parameters: {'learning_rate': 0.004644220221410866, 'n_estimators': 227, 'max_depth': 18}. Best is trial 5 with value: 0.9506601220522692.\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "[I 2025-08-15 15:23:57,433] Trial 9 finished with value: 0.9098284043881577 and parameters: {'learning_rate': 0.055019560507236547, 'n_estimators': 436, 'max_depth': 3}. Best is trial 5 with value: 0.9506601220522692.\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "[I 2025-08-15 15:23:57,433] Trial 9 finished with value: 0.9098284043881577 and parameters: {'learning_rate': 0.055019560507236547, 'n_estimators': 436, 'max_depth': 3}. Best is trial 5 with value: 0.9506601220522692.\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "[I 2025-08-15 15:24:17,059] Trial 10 finished with value: 0.9266698345323907 and parameters: {'learning_rate': 0.033991008146033626, 'n_estimators': 396, 'max_depth': 8}. Best is trial 5 with value: 0.9506601220522692.\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "[I 2025-08-15 15:24:17,059] Trial 10 finished with value: 0.9266698345323907 and parameters: {'learning_rate': 0.033991008146033626, 'n_estimators': 396, 'max_depth': 8}. Best is trial 5 with value: 0.9506601220522692.\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "[I 2025-08-15 15:24:34,437] Trial 11 finished with value: 0.9487742090722134 and parameters: {'learning_rate': 0.07590624236967937, 'n_estimators': 339, 'max_depth': 10}. Best is trial 5 with value: 0.9506601220522692.\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "[I 2025-08-15 15:24:34,437] Trial 11 finished with value: 0.9487742090722134 and parameters: {'learning_rate': 0.07590624236967937, 'n_estimators': 339, 'max_depth': 10}. Best is trial 5 with value: 0.9506601220522692.\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "[I 2025-08-15 15:24:51,207] Trial 12 finished with value: 0.9471076174187608 and parameters: {'learning_rate': 0.07673398369438568, 'n_estimators': 347, 'max_depth': 9}. Best is trial 5 with value: 0.9506601220522692.\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "[I 2025-08-15 15:24:51,207] Trial 12 finished with value: 0.9471076174187608 and parameters: {'learning_rate': 0.07673398369438568, 'n_estimators': 347, 'max_depth': 9}. Best is trial 5 with value: 0.9506601220522692.\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "[I 2025-08-15 15:25:08,959] Trial 13 finished with value: 0.9511863570582818 and parameters: {'learning_rate': 0.09946802650480219, 'n_estimators': 349, 'max_depth': 10}. Best is trial 13 with value: 0.9511863570582818.\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "[I 2025-08-15 15:25:08,959] Trial 13 finished with value: 0.9511863570582818 and parameters: {'learning_rate': 0.09946802650480219, 'n_estimators': 349, 'max_depth': 10}. Best is trial 13 with value: 0.9511863570582818.\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "[I 2025-08-15 15:25:19,038] Trial 14 finished with value: 0.9380728470630596 and parameters: {'learning_rate': 0.0951364131493829, 'n_estimators': 315, 'max_depth': 5}. Best is trial 13 with value: 0.9511863570582818.\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "[I 2025-08-15 15:25:19,038] Trial 14 finished with value: 0.9380728470630596 and parameters: {'learning_rate': 0.0951364131493829, 'n_estimators': 315, 'max_depth': 5}. Best is trial 13 with value: 0.9511863570582818.\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "[I 2025-08-15 15:25:47,232] Trial 15 finished with value: 0.9549581945588876 and parameters: {'learning_rate': 0.09958186549423878, 'n_estimators': 473, 'max_depth': 16}. Best is trial 15 with value: 0.9549581945588876.\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "[I 2025-08-15 15:25:47,232] Trial 15 finished with value: 0.9549581945588876 and parameters: {'learning_rate': 0.09958186549423878, 'n_estimators': 473, 'max_depth': 16}. Best is trial 15 with value: 0.9549581945588876.\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "[I 2025-08-15 15:26:18,303] Trial 16 finished with value: 0.9549582003291349 and parameters: {'learning_rate': 0.09784602901436658, 'n_estimators': 482, 'max_depth': 17}. Best is trial 16 with value: 0.9549582003291349.\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "[I 2025-08-15 15:26:18,303] Trial 16 finished with value: 0.9549582003291349 and parameters: {'learning_rate': 0.09784602901436658, 'n_estimators': 482, 'max_depth': 17}. Best is trial 16 with value: 0.9549582003291349.\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "[I 2025-08-15 15:26:49,857] Trial 17 finished with value: 0.9504847296177558 and parameters: {'learning_rate': 0.038998430961036085, 'n_estimators': 490, 'max_depth': 17}. Best is trial 16 with value: 0.9549582003291349.\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "[I 2025-08-15 15:26:49,857] Trial 17 finished with value: 0.9504847296177558 and parameters: {'learning_rate': 0.038998430961036085, 'n_estimators': 490, 'max_depth': 17}. Best is trial 16 with value: 0.9549582003291349.\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "[I 2025-08-15 15:27:19,982] Trial 18 finished with value: 0.9544757672697729 and parameters: {'learning_rate': 0.08403102806737418, 'n_estimators': 498, 'max_depth': 20}. Best is trial 16 with value: 0.9549582003291349.\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "[I 2025-08-15 15:27:19,982] Trial 18 finished with value: 0.9544757672697729 and parameters: {'learning_rate': 0.08403102806737418, 'n_estimators': 498, 'max_depth': 20}. Best is trial 16 with value: 0.9549582003291349.\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "[I 2025-08-15 15:27:46,340] Trial 19 finished with value: 0.9505285431049009 and parameters: {'learning_rate': 0.041608372612506196, 'n_estimators': 428, 'max_depth': 18}. Best is trial 16 with value: 0.9549582003291349.\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "[I 2025-08-15 15:27:46,340] Trial 19 finished with value: 0.9505285431049009 and parameters: {'learning_rate': 0.041608372612506196, 'n_estimators': 428, 'max_depth': 18}. Best is trial 16 with value: 0.9549582003291349.\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "[I 2025-08-15 15:28:14,979] Trial 20 finished with value: 0.9539494630207935 and parameters: {'learning_rate': 0.06944998418482366, 'n_estimators': 451, 'max_depth': 18}. Best is trial 16 with value: 0.9549582003291349.\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "[I 2025-08-15 15:28:14,979] Trial 20 finished with value: 0.9539494630207935 and parameters: {'learning_rate': 0.06944998418482366, 'n_estimators': 451, 'max_depth': 18}. Best is trial 16 with value: 0.9549582003291349.\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "[I 2025-08-15 15:28:43,344] Trial 21 finished with value: 0.9532477317158176 and parameters: {'learning_rate': 0.08646256708489031, 'n_estimators': 500, 'max_depth': 20}. Best is trial 16 with value: 0.9549582003291349.\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "[I 2025-08-15 15:28:43,344] Trial 21 finished with value: 0.9532477317158176 and parameters: {'learning_rate': 0.08646256708489031, 'n_estimators': 500, 'max_depth': 20}. Best is trial 16 with value: 0.9549582003291349.\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "[I 2025-08-15 15:29:08,607] Trial 22 finished with value: 0.9543003171327872 and parameters: {'learning_rate': 0.09352371434290185, 'n_estimators': 398, 'max_depth': 20}. Best is trial 16 with value: 0.9549582003291349.\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "[I 2025-08-15 15:29:08,607] Trial 22 finished with value: 0.9543003171327872 and parameters: {'learning_rate': 0.09352371434290185, 'n_estimators': 398, 'max_depth': 20}. Best is trial 16 with value: 0.9549582003291349.\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "[I 2025-08-15 15:29:34,329] Trial 23 finished with value: 0.9542125401320695 and parameters: {'learning_rate': 0.08216589523224123, 'n_estimators': 469, 'max_depth': 16}. Best is trial 16 with value: 0.9549582003291349.\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "[I 2025-08-15 15:29:34,329] Trial 23 finished with value: 0.9542125401320695 and parameters: {'learning_rate': 0.08216589523224123, 'n_estimators': 469, 'max_depth': 16}. Best is trial 16 with value: 0.9549582003291349.\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "[I 2025-08-15 15:30:05,676] Trial 24 finished with value: 0.9541687381854188 and parameters: {'learning_rate': 0.09289853014046703, 'n_estimators': 404, 'max_depth': 19}. Best is trial 16 with value: 0.9549582003291349.\n",
            "[I 2025-08-15 15:30:05,676] Trial 24 finished with value: 0.9541687381854188 and parameters: {'learning_rate': 0.09289853014046703, 'n_estimators': 404, 'max_depth': 19}. Best is trial 16 with value: 0.9549582003291349.\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "[I 2025-08-15 15:30:40,027] Trial 25 finished with value: 0.9545634807977713 and parameters: {'learning_rate': 0.08149349934938906, 'n_estimators': 473, 'max_depth': 16}. Best is trial 16 with value: 0.9549582003291349.\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "[I 2025-08-15 15:30:40,027] Trial 25 finished with value: 0.9545634807977713 and parameters: {'learning_rate': 0.08149349934938906, 'n_estimators': 473, 'max_depth': 16}. Best is trial 16 with value: 0.9549582003291349.\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "[I 2025-08-15 15:31:05,556] Trial 26 finished with value: 0.9544319076206501 and parameters: {'learning_rate': 0.09994627120295485, 'n_estimators': 458, 'max_depth': 15}. Best is trial 16 with value: 0.9549582003291349.\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "[I 2025-08-15 15:31:05,556] Trial 26 finished with value: 0.9544319076206501 and parameters: {'learning_rate': 0.09994627120295485, 'n_estimators': 458, 'max_depth': 15}. Best is trial 16 with value: 0.9549582003291349.\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "[I 2025-08-15 15:31:26,967] Trial 27 finished with value: 0.9502215024800522 and parameters: {'learning_rate': 0.0676361142163237, 'n_estimators': 376, 'max_depth': 12}. Best is trial 16 with value: 0.9549582003291349.\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "[I 2025-08-15 15:31:26,967] Trial 27 finished with value: 0.9502215024800522 and parameters: {'learning_rate': 0.0676361142163237, 'n_estimators': 376, 'max_depth': 12}. Best is trial 16 with value: 0.9549582003291349.\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "[I 2025-08-15 15:31:58,320] Trial 28 finished with value: 0.9540371303868143 and parameters: {'learning_rate': 0.07916977931817692, 'n_estimators': 432, 'max_depth': 16}. Best is trial 16 with value: 0.9549582003291349.\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "[I 2025-08-15 15:31:58,320] Trial 28 finished with value: 0.9540371303868143 and parameters: {'learning_rate': 0.07916977931817692, 'n_estimators': 432, 'max_depth': 16}. Best is trial 16 with value: 0.9549582003291349.\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "[I 2025-08-15 15:32:30,919] Trial 29 finished with value: 0.9363185880435863 and parameters: {'learning_rate': 0.01801097298777673, 'n_estimators': 470, 'max_depth': 17}. Best is trial 16 with value: 0.9549582003291349.\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "[I 2025-08-15 15:32:30,919] Trial 29 finished with value: 0.9363185880435863 and parameters: {'learning_rate': 0.01801097298777673, 'n_estimators': 470, 'max_depth': 17}. Best is trial 16 with value: 0.9549582003291349.\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "[I 2025-08-15 15:32:47,311] Trial 30 finished with value: 0.9377220621940326 and parameters: {'learning_rate': 0.047741270782411756, 'n_estimators': 208, 'max_depth': 15}. Best is trial 16 with value: 0.9549582003291349.\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "[I 2025-08-15 15:32:47,311] Trial 30 finished with value: 0.9377220621940326 and parameters: {'learning_rate': 0.047741270782411756, 'n_estimators': 208, 'max_depth': 15}. Best is trial 16 with value: 0.9549582003291349.\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "[I 2025-08-15 15:33:19,030] Trial 31 finished with value: 0.9545196326891429 and parameters: {'learning_rate': 0.08378626735118967, 'n_estimators': 500, 'max_depth': 17}. Best is trial 16 with value: 0.9549582003291349.\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "[I 2025-08-15 15:33:19,030] Trial 31 finished with value: 0.9545196326891429 and parameters: {'learning_rate': 0.08378626735118967, 'n_estimators': 500, 'max_depth': 17}. Best is trial 16 with value: 0.9549582003291349.\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "[I 2025-08-15 15:33:44,822] Trial 32 finished with value: 0.9544757095673008 and parameters: {'learning_rate': 0.09993772297231364, 'n_estimators': 468, 'max_depth': 17}. Best is trial 16 with value: 0.9549582003291349.\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "[I 2025-08-15 15:33:44,822] Trial 32 finished with value: 0.9544757095673008 and parameters: {'learning_rate': 0.09993772297231364, 'n_estimators': 468, 'max_depth': 17}. Best is trial 16 with value: 0.9549582003291349.\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "[I 2025-08-15 15:34:05,202] Trial 33 finished with value: 0.9543003748352593 and parameters: {'learning_rate': 0.09106062754498465, 'n_estimators': 431, 'max_depth': 14}. Best is trial 16 with value: 0.9549582003291349.\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "[I 2025-08-15 15:34:05,202] Trial 33 finished with value: 0.9543003748352593 and parameters: {'learning_rate': 0.09106062754498465, 'n_estimators': 431, 'max_depth': 14}. Best is trial 16 with value: 0.9549582003291349.\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "[I 2025-08-15 15:34:34,130] Trial 34 finished with value: 0.9539494572505465 and parameters: {'learning_rate': 0.06931794190420104, 'n_estimators': 480, 'max_depth': 16}. Best is trial 16 with value: 0.9549582003291349.\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "[I 2025-08-15 15:34:34,130] Trial 34 finished with value: 0.9539494572505465 and parameters: {'learning_rate': 0.06931794190420104, 'n_estimators': 480, 'max_depth': 16}. Best is trial 16 with value: 0.9549582003291349.\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "[I 2025-08-15 15:34:58,626] Trial 35 finished with value: 0.9544757845805146 and parameters: {'learning_rate': 0.08653784593378339, 'n_estimators': 410, 'max_depth': 19}. Best is trial 16 with value: 0.9549582003291349.\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "[I 2025-08-15 15:34:58,626] Trial 35 finished with value: 0.9544757845805146 and parameters: {'learning_rate': 0.08653784593378339, 'n_estimators': 410, 'max_depth': 19}. Best is trial 16 with value: 0.9549582003291349.\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "[I 2025-08-15 15:35:17,795] Trial 36 finished with value: 0.9532477086348288 and parameters: {'learning_rate': 0.09450292799874889, 'n_estimators': 370, 'max_depth': 12}. Best is trial 16 with value: 0.9549582003291349.\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "[I 2025-08-15 15:35:17,795] Trial 36 finished with value: 0.9532477086348288 and parameters: {'learning_rate': 0.09450292799874889, 'n_estimators': 370, 'max_depth': 12}. Best is trial 16 with value: 0.9549582003291349.\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "[I 2025-08-15 15:35:22,986] Trial 37 finished with value: 0.902065644640479 and parameters: {'learning_rate': 0.06172075510372541, 'n_estimators': 75, 'max_depth': 14}. Best is trial 16 with value: 0.9549582003291349.\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "[I 2025-08-15 15:35:22,986] Trial 37 finished with value: 0.902065644640479 and parameters: {'learning_rate': 0.06172075510372541, 'n_estimators': 75, 'max_depth': 14}. Best is trial 16 with value: 0.9549582003291349.\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "[I 2025-08-15 15:35:48,486] Trial 38 finished with value: 0.954431878769414 and parameters: {'learning_rate': 0.081031667108997, 'n_estimators': 450, 'max_depth': 16}. Best is trial 16 with value: 0.9549582003291349.\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "[I 2025-08-15 15:35:48,486] Trial 38 finished with value: 0.954431878769414 and parameters: {'learning_rate': 0.081031667108997, 'n_estimators': 450, 'max_depth': 16}. Best is trial 16 with value: 0.9549582003291349.\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "[I 2025-08-15 15:36:06,048] Trial 39 finished with value: 0.9521512981902197 and parameters: {'learning_rate': 0.07170836257110746, 'n_estimators': 276, 'max_depth': 18}. Best is trial 16 with value: 0.9549582003291349.\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "[I 2025-08-15 15:36:06,048] Trial 39 finished with value: 0.9521512981902197 and parameters: {'learning_rate': 0.07170836257110746, 'n_estimators': 276, 'max_depth': 18}. Best is trial 16 with value: 0.9549582003291349.\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "[I 2025-08-15 15:36:23,640] Trial 40 finished with value: 0.9527214101560967 and parameters: {'learning_rate': 0.08982917933342044, 'n_estimators': 306, 'max_depth': 13}. Best is trial 16 with value: 0.9549582003291349.\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "[I 2025-08-15 15:36:23,640] Trial 40 finished with value: 0.9527214101560967 and parameters: {'learning_rate': 0.08982917933342044, 'n_estimators': 306, 'max_depth': 13}. Best is trial 16 with value: 0.9549582003291349.\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "[I 2025-08-15 15:36:45,157] Trial 41 finished with value: 0.9543880710525162 and parameters: {'learning_rate': 0.08552900300643083, 'n_estimators': 406, 'max_depth': 19}. Best is trial 16 with value: 0.9549582003291349.\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "[I 2025-08-15 15:36:45,157] Trial 41 finished with value: 0.9543880710525162 and parameters: {'learning_rate': 0.08552900300643083, 'n_estimators': 406, 'max_depth': 19}. Best is trial 16 with value: 0.9549582003291349.\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "[I 2025-08-15 15:37:12,326] Trial 42 finished with value: 0.9540371707785448 and parameters: {'learning_rate': 0.08755080335220494, 'n_estimators': 480, 'max_depth': 19}. Best is trial 16 with value: 0.9549582003291349.\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "[I 2025-08-15 15:37:12,326] Trial 42 finished with value: 0.9540371707785448 and parameters: {'learning_rate': 0.08755080335220494, 'n_estimators': 480, 'max_depth': 19}. Best is trial 16 with value: 0.9549582003291349.\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "[I 2025-08-15 15:37:35,953] Trial 43 finished with value: 0.9539933284401637 and parameters: {'learning_rate': 0.07432136090392377, 'n_estimators': 449, 'max_depth': 17}. Best is trial 16 with value: 0.9549582003291349.\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "[I 2025-08-15 15:37:35,953] Trial 43 finished with value: 0.9539933284401637 and parameters: {'learning_rate': 0.07432136090392377, 'n_estimators': 449, 'max_depth': 17}. Best is trial 16 with value: 0.9549582003291349.\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "[I 2025-08-15 15:37:58,294] Trial 44 finished with value: 0.9544319249313918 and parameters: {'learning_rate': 0.09715900374885444, 'n_estimators': 415, 'max_depth': 19}. Best is trial 16 with value: 0.9549582003291349.\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "[I 2025-08-15 15:37:58,294] Trial 44 finished with value: 0.9544319249313918 and parameters: {'learning_rate': 0.09715900374885444, 'n_estimators': 415, 'max_depth': 19}. Best is trial 16 with value: 0.9549582003291349.\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "[I 2025-08-15 15:38:01,996] Trial 45 finished with value: 0.8992148540012049 and parameters: {'learning_rate': 0.08059809513237137, 'n_estimators': 51, 'max_depth': 15}. Best is trial 16 with value: 0.9549582003291349.\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "[I 2025-08-15 15:38:01,996] Trial 45 finished with value: 0.8992148540012049 and parameters: {'learning_rate': 0.08059809513237137, 'n_estimators': 51, 'max_depth': 15}. Best is trial 16 with value: 0.9549582003291349.\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "[I 2025-08-15 15:38:23,421] Trial 46 finished with value: 0.9403534911149732 and parameters: {'learning_rate': 0.02433664918226583, 'n_estimators': 381, 'max_depth': 18}. Best is trial 16 with value: 0.9549582003291349.\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "[I 2025-08-15 15:38:23,421] Trial 46 finished with value: 0.9403534911149732 and parameters: {'learning_rate': 0.02433664918226583, 'n_estimators': 381, 'max_depth': 18}. Best is trial 16 with value: 0.9549582003291349.\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "[I 2025-08-15 15:38:49,304] Trial 47 finished with value: 0.9545635211895019 and parameters: {'learning_rate': 0.09033493634632916, 'n_estimators': 497, 'max_depth': 17}. Best is trial 16 with value: 0.9549582003291349.\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "[I 2025-08-15 15:38:49,304] Trial 47 finished with value: 0.9545635211895019 and parameters: {'learning_rate': 0.09033493634632916, 'n_estimators': 497, 'max_depth': 17}. Best is trial 16 with value: 0.9549582003291349.\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "[I 2025-08-15 15:38:59,110] Trial 48 finished with value: 0.9363185880435863 and parameters: {'learning_rate': 0.056038847197472624, 'n_estimators': 183, 'max_depth': 14}. Best is trial 16 with value: 0.9549582003291349.\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "[I 2025-08-15 15:38:59,110] Trial 48 finished with value: 0.9363185880435863 and parameters: {'learning_rate': 0.056038847197472624, 'n_estimators': 183, 'max_depth': 14}. Best is trial 16 with value: 0.9549582003291349.\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "[I 2025-08-15 15:39:24,736] Trial 49 finished with value: 0.9545634923382657 and parameters: {'learning_rate': 0.09093135726032055, 'n_estimators': 498, 'max_depth': 15}. Best is trial 16 with value: 0.9549582003291349.\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "[I 2025-08-15 15:39:24,736] Trial 49 finished with value: 0.9545634923382657 and parameters: {'learning_rate': 0.09093135726032055, 'n_estimators': 498, 'max_depth': 15}. Best is trial 16 with value: 0.9549582003291349.\n"
          ]
        },
        {
          "name": "stdout",
          "output_type": "stream",
          "text": [
            "{'learning_rate': 0.09784602901436658, 'n_estimators': 482, 'max_depth': 17}\n"
          ]
        }
      ],
      "source": [
        "# Create an Optuna study to optimize the hyperparameters\n",
        "study = optuna.create_study(direction=\"maximize\")\n",
        "study.optimize(objective, n_trials=50)\n",
        "\n",
        "# Extract the best hyperparameters\n",
        "best_params = study.best_params\n",
        "print(best_params)"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 38,
      "metadata": {},
      "outputs": [
        {
          "data": {
            "text/plain": [
              "{'learning_rate': 0.09784602901436658, 'n_estimators': 482, 'max_depth': 17}"
            ]
          },
          "execution_count": 38,
          "metadata": {},
          "output_type": "execute_result"
        }
      ],
      "source": [
        "best_params = study.best_params\n",
        "best_params"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 32,
      "metadata": {},
      "outputs": [],
      "source": [
        "# Create the best model using tuned hyperparameters\n",
        "best_model = LGBMClassifier(\n",
        "    objective=\"multiclass\",\n",
        "    num_class=3,\n",
        "    metric=\"multi_logloss\",\n",
        "    is_unbalance=True,\n",
        "    class_weight=\"balanced\",\n",
        "    reg_alpha=0.1,  # L1 regularization\n",
        "    reg_lambda=0.1,  # L2 regularization\n",
        "    learning_rate=best_params[\"learning_rate\"],\n",
        "    max_depth=best_params[\"max_depth\"],\n",
        "    n_estimators=best_params[\"n_estimators\"]\n",
        ")"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 33,
      "metadata": {},
      "outputs": [
        {
          "name": "stderr",
          "output_type": "stream",
          "text": [
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n"
          ]
        },
        {
          "name": "stdout",
          "output_type": "stream",
          "text": [
            "Train Accuracy: 0.9902635849304855\n"
          ]
        }
      ],
      "source": [
        "# Fit the model on the resampled training data\n",
        "best_model.fit(X_train_tfidf_cleaned, y_train_cleaned)\n",
        "\n",
        "# Predict on the train set\n",
        "y_train_pred = best_model.predict(X_train_tfidf_cleaned)\n",
        "\n",
        "# Calculate accuracy on the train set\n",
        "accuracy_train = accuracy_score(y_train_cleaned, y_train_pred)\n",
        "print(\"Train Accuracy:\", accuracy_train)"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 34,
      "metadata": {},
      "outputs": [
        {
          "name": "stdout",
          "output_type": "stream",
          "text": [
            "              precision    recall  f1-score   support\n",
            "\n",
            "         0.0       0.98      1.00      0.99     10169\n",
            "         1.0       1.00      0.98      0.99     12632\n",
            "\n",
            "    accuracy                           0.99     22801\n",
            "   macro avg       0.99      0.99      0.99     22801\n",
            "weighted avg       0.99      0.99      0.99     22801\n",
            "\n"
          ]
        }
      ],
      "source": [
        "# Generate classification report\n",
        "report_train = classification_report(y_train_cleaned, y_train_pred)\n",
        "print(report_train)"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 36,
      "metadata": {},
      "outputs": [],
      "source": [
        "import numpy as np \n",
        "import re \n",
        "\n",
        "# Function to clean and preprocess a YouTube comment (same as used during training)\n",
        "def preprocess_comment(comment):\n",
        "    # Lowercasing\n",
        "    comment = comment.lower()\n",
        "\n",
        "    # Remove special characters, URLs, punctuation, and extra spaces\n",
        "    comment = re.sub(r\"http\\S+|www\\S+|https\\S+\", ' ', comment, flags=re.MULTILINE)  # Remove URLs\n",
        "    comment = re.sub(r\"\\W\", \" \", comment)  # Remove special characters\n",
        "    comment = re.sub(r\"\\s+\", \" \", comment).strip()  # Remove extra spaces and newlines\n",
        "\n",
        "    return comment\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 37,
      "metadata": {},
      "outputs": [
        {
          "name": "stdout",
          "output_type": "stream",
          "text": [
            "{'sentiment_class': 1, 'confidence': 0.8871236069577338}\n"
          ]
        },
        {
          "name": "stderr",
          "output_type": "stream",
          "text": [
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n",
            "c:\\Users\\Deepu\\anaconda3\\envs\\nlp\\lib\\site-packages\\sklearn\\utils\\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names\n",
            "  warnings.warn(\n"
          ]
        }
      ],
      "source": [
        "# Prediction function\n",
        "def predict_sentiment(comment, tfidf_vectorizer, lgbm_model):\n",
        "    # Step 1: Preprocess the YouTube comment\n",
        "    cleaned_comment = preprocess_comment(comment)\n",
        "\n",
        "    # Step 2: Transform the comment using the trained TF-IDF vectorizer\n",
        "    comment_tfidf = tfidf_vectorizer.transform([cleaned_comment])\n",
        "\n",
        "    # Step 3: Use the trained LightGBM model to predict the sentiment\n",
        "    prediction = lgbm_model.predict(comment_tfidf)\n",
        "    prediction_proba = lgbm_model.predict_proba(comment_tfidf)\n",
        "\n",
        "    # Step 4: Get the predicted sentiment (label) and probability\n",
        "    sentiment_class = np.argmax(prediction_proba)\n",
        "    sentiment_proba = np.max(prediction_proba)\n",
        "\n",
        "    # Step 5: Return the sentiment label and confidence\n",
        "    return {\n",
        "        'sentiment_class': int(prediction[0]),  # e.g., -1, 0, or 1 depending on your labels\n",
        "        'confidence': sentiment_proba\n",
        "    }\n",
        "\n",
        "# Example usage:\n",
        "comment = \"I absolutely hate this video!\"\n",
        "result = predict_sentiment(comment, TF_IDF_cleaned, best_model)\n",
        "print(result)\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": []
    }
  ],
  "metadata": {
    "colab": {
      "provenance": []
    },
    "kernelspec": {
      "display_name": "nlp",
      "language": "python",
      "name": "python3"
    },
    "language_info": {
      "codemirror_mode": {
        "name": "ipython",
        "version": 3
      },
      "file_extension": ".py",
      "mimetype": "text/x-python",
      "name": "python",
      "nbconvert_exporter": "python",
      "pygments_lexer": "ipython3",
      "version": "3.10.18"
    }
  },
  "nbformat": 4,
  "nbformat_minor": 0
}
